Factory/Models/DesignTimeDbContextFactor.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.EngineerMachineEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public Work IsWorking { get; set; }

    public DateTime DateOfHire { get; set; }

    public DateTime DateOfLicense { get; set; }
    public virtual ICollection<EngineerMachine> EngineerMachineEntities { get; set; }
  }

  public enum Work
  {
    Idle,
    Occupied
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int MachineId { get; set; }
    public int EngineerId { get; set; }
    public virtual Machine Machine { get; set; }
    public virtual Engineer Engineer { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines{ get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.EngineerMachineEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public Operation IsOperational { get; set; }
    public DateTime DateOfInspection { get; set; }
    // public DateTime DateOfInstall { get; set; }

    public virtual ICollection<EngineerMachine> EngineerMachineEntities { get; }
  }

  public enum Operation
  {
    Functioning,
    Broken,

    Servicing
  }

}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }


    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
          .Include(engineer => engineer.EngineerMachineEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
          .Include(machine => machine.EngineerMachineEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a machine</h2>

<h4>Add a machine to this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to engineer", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
@{
  Layout = "_Layout";
}
<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>Add New Engineer</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">

        @using (Html.BeginForm())
        {
          @Html.LabelFor(model => model.Name)
          @Html.TextBoxFor(model => model.Name)
          <br>
          @Html.LabelFor(model => model.DateOfHire)
          @Html.TextBoxFor(model => model.DateOfHire)
          <br>
          @Html.LabelFor(model => model.DateOfLicense)
          @Html.TextBoxFor(model => model.DateOfLicense)
          <br>
          @Html.LabelFor(model => model.IsWorking)
          @Html.DropDownList("Working", new List<SelectListItem>
        {
        new SelectListItem { Text = "Idle", Value = "Idle"},
        new SelectListItem { Text = "Occupied", Value = "Occupied"},
        }, "Select Status")
          <br>
          <input type="submit" value="Add new engineer" />
        }
        <br>
        <button>@Html.ActionLink("Show all engineers", "Index")</button>
      </p>
    </div>
  </div>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Engineers", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h2>Engineer Details</h2>
<hr />

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date of Hire</th>
      <th scope="col">Date of License</th>
      <th scope="col">Working</th>
    </tr>
  </thead>
  <tr>
    <td>@Html.DisplayFor(model => model.Name)</td>
    <td>@Html.DisplayFor(model => model.DateOfHire)</td>
    <td>@Html.DisplayFor(model=> model.DateOfLicense)</td>
    <td>@Html.DisplayFor(model=>model.IsWorking)</td>
  </tr>
  </tbody>
</table>


@if (@Model.EngineerMachineEntities.Count == 0)
{
  <p>This engineer does not work on any machines</p>
}
else
{
  <h4>Machines the engineer has/currently working on:</h4>

  @foreach (var join in Model.EngineerMachineEntities)
  {
    <p>@Html.ActionLink($"{join.Machine.Name}", "Details", "Machines", new {id = join.MachineId}) </p>
    <br>
    <p>@join.Machine.IsOperational</p>
    <br>
    <p>@join.Machine.DateOfInspection </p>
  }
}

<br>
<button>@Html.ActionLink("Back to engineers", "Index")</button>
<button>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</button>
<button>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</button>
<button>@Html.ActionLink("Add a machine", "AddMachine", new { id = Model.EngineerId })</button>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>Edit Engineer</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">


        @using (Html.BeginForm())
        {
          @Html.HiddenFor(model => model.EngineerId)

          @Html.LabelFor(model => model.Name)
          @Html.EditorFor(model => model.Name)
          <br>
          @Html.LabelFor(model => model.DateOfHire)
          @Html.TextBoxFor(model => model.DateOfHire)
          <br>
          @Html.LabelFor(model => model.DateOfLicense)
          @Html.TextBoxFor(model => model.DateOfLicense)
          <br>

          @Html.LabelFor(model => model.IsWorking)
          @Html.DropDownList("Status", new List<SelectListItem>
        {
        new SelectListItem { Text = "Idle", Value = "false"},
        new SelectListItem { Text = "Occupied", Value = "true"},
        }, "Select Status")
          <br>
          <input type="submit" value="Save" />
          <br>
        }

        @Html.ActionLink("Back to Engineers", "Index")
      </p>
      </p>
    </div>
  </div>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models;
@model List<Factory.Models.Engineer>;

<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>The Engineers</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">

        @if (@Model.Count == 0)
        {
        <h3>No engineers have been added yet!</h3>
        }

        @foreach (Engineer engineer in @Model)
        {

          @Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })
        <br>
          @foreach (var machine in @engineer.EngineerMachineEntities)
          {
            @machine.Machine.Name
          <br>
          }
        }
      <br>
      <button>@Html.ActionLink("Add new engineer", "Create")</button>
      <br>
      <button>@Html.ActionLink("Home", "Index", "Home")</button>
      </p>
    </div>
  </div>
</div>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>The Factory</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">
        @Html.ActionLink("See all Engineers", "Index", "Engineers")
        <br>
        @Html.ActionLink("See all Machines", "Index", "Machines")
      </p>
    </div>
  </div>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a engineer</h2>

<h4>Add a engineer to this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine

<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>Add a Machine</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">
        @using (Html.BeginForm())
        {
          @Html.LabelFor(model => model.Name)
          @Html.TextBoxFor(model => model.Name)
          <br>
          @Html.LabelFor(model => model.IsOperational)
          @Html.DropDownList("Operation", new List<SelectListItem>
        {
        new SelectListItem { Text = "Functioning", Value = "Functioning"},
        new SelectListItem { Text = "Broken ", Value = "Broken"},
        new SelectListItem {Text = "Servicing", Value ="Servicing"}
        }, "Select Operationality")
          <br>

          @Html.LabelFor(model => model.DateOfInspection)
          @Html.TextBoxFor(model => model.DateOfInspection)

          <br>
          <button><input type="submit" value="Add new machine" /></button>
        }
        <br>
        <button> @Html.ActionLink("Show all machines", "Index") </button>
        <br>
      </p>
    </div>
  </div>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this machine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<br>
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<h1>Your machine has been cleared!</h1>
<p><a href="/machines">Back to list.</a></p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Machine Details for @Html.DisplayFor(model => model.Name)</h3>
<hr />
<table class="table">
  <thead>
    <tr>
      <th scope="col">Date of Inspection</th>
      <th scope="col">Operational</th>
    </tr>
  </thead>
  <tr>
    <td>@Html.DisplayFor(model =>model.DateOfInspection)</td>
    <td>Machine Operational: @Html.DisplayFor(model=>model.IsOperational)</td>
  </tr>
  </tbody>
</table>


@if (@Model.EngineerMachineEntities.Count == 0)
{
  <p>This machine is too hard for our Engineers!</p>
}
else
{
  <h4>Engineers that can work on the machine:</h4>

  @foreach (var join in Model.EngineerMachineEntities)
  {
    <p> @join.Engineer.Name </p>
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      <p>@Html.Hidden("joinId", @join.EngineerMachineId)</p>
      <input type="submit" value="Delete" />

    }
  }
}

<button type="button">@Html.ActionLink("Back to Machine", "Index")</button>
<button type="button">@Html.ActionLink("Edit Machine", "Edit", new { id =
  Model.MachineId })</button>
<button type="button">@Html.ActionLink("Delete Machine", "Delete", new { id =
  Model.MachineId })</button>
<button type="button">@Html.ActionLink("Add a Engineer", "AddEngineer", new { id =
  Model.MachineId })</button>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>Editing Machine</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">

        @model Factory.Models.Machine

      <h2>Edit this Machine: </h2>
      <h4>@Html.DisplayFor(model => model.Name)</h4>

      @using (Html.BeginForm())
        {
          @Html.HiddenFor(model => model.MachineId)

          @Html.LabelFor(model => model.Name)
          @Html.TextBoxFor(model => model.Name)
        <br>
          @Html.LabelFor(model => model.IsOperational)
          @Html.DropDownList("Is Operational", new List<SelectListItem>
      {
      new SelectListItem { Text = "Functioning Well", Value = "Functional"},
      new SelectListItem { Text = "Needs Maintenance ", Value = "Needs Maintenance"},
      }, "Select Status")

        <br>
          @Html.LabelFor(model => model.DateOfInspection)
          @Html.TextBoxFor(model => model.DateOfInspection)
        <br>
          @Html.Label("Select engineer")
          @Html.DropDownList("EngineerId")

        <button><input type="submit" value="Save" /> </button>
        }

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models;
@model List<Factory.Models.Machine>;

<div class="home">

  <div class="card border-secondary mb-3 mt-5" style="max-width: 60rem;">
    <div class="card-header">
      <h1>The Machines</h1>
    </div>
    <div class="card-body">
      <h4 class="card-title"></h4>
      <p class="card-text">

        @if (@Model.Count == 0)
        {
        <h3>No machines have been added yet!</h3>
        }

        @foreach (Machine machine in Model)
        {
        <br>
          @Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })
        <br>
        }
      <br>
      <button>@Html.ActionLink("Add new machine", "Create")</button>
      <br>
      <button>@Html.ActionLink("Home", "Index", "Home")</button>

      </p>
    </div>
  </div>
</div>

Factory/Views/Shared/Footer.cshtml
<div id="footer">See what is working! </div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Factory!</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="~/css/styles.css" />
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Factory</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
        aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="/">Home
              <span class="visually-hidden"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../Engineers/Index">Engineers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../Machines/Index">Machines</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
              aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="../Engineers/Create">Add a Engineer</a>
              <a class="dropdown-item" href="../Machines/Create">Add a Machines</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>

<body>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>
</body>

</html>